from szbot import sz
from requests import get
from pyrogram import filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from szbot.helpers.fsub import ForceSub
import requests


@sz.on_message(filters.command("logo"))
@ForceSub
async def on_off_antiarab(_, message: Message):
    text = message.text.split(None, 1)[1]
    lol = get((f"https://single-developers.up.railway.app/logo?name={text}").replace(' ','%20')).history[1].url
    caption = f"""
logo Genarated Successfully✅

࿂ **Generated By** : [szrosebot](https://t.me/szrosebot)
࿂ **Requestor** :. {message.from_user.mention}
࿂ **Powered By **  : [szteambots](https://t.me/szteambots)
࿂ **Download link** : `{lol}`
"""        
    await sz.send_photo(message.chat.id, photo=lol, caption =caption.format(message.from_user.mention),
                 reply_markup=InlineKeyboardMarkup(
            [
                [
                    InlineKeyboardButton(
                        "••Telegraph Link••", url=f"{lol}"
                    )
                ]
            ]
          ),
    )
#hq logo creator
@sz.on_message(filters.command("logohq"))
@ForceSub
async def on_off_antiarab(_, message: Message):
    text = message.text.split(None, 1)[1]
    photo = get((f"https://single-developers.up.railway.app/logohq?name={text}").replace(' ','%20')).history[1].url
    caption = f"""
HQlogo Genarated Successfully✅

࿂ **Generated By** : [szrosebot](https://t.me/szrosebot)
࿂ **Requestor** :. {message.from_user.mention}
࿂ **Powered By **  : [szteambots](https://t.me/szteambots)
࿂ **Download link** : `{photo}`
"""    
    await sz.send_photo(message.chat.id, photo=photo, caption =caption.format(message.from_user.mention),
                 reply_markup=InlineKeyboardMarkup(
            [
                [
                    InlineKeyboardButton(
                        "••Telegraph Link••", url=f"{photo}"
                    )
                ]
            ]
          ),
    )
